// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhL_H1TH5-nP2_bGiUn77FzGUslOqFsOc',
    appId: '1:982171502878:web:3c14d6bb69a68c58ac210f',
    messagingSenderId: '982171502878',
    projectId: 'clontwitter',
    authDomain: 'clontwitter.firebaseapp.com',
    storageBucket: 'clontwitter.firebasestorage.app',
    measurementId: 'G-GS6LD3FWLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4XWlEwrcX3Cj2IuDemztguN5s6WRyuWw',
    appId: '1:982171502878:android:4d88984d90aca136ac210f',
    messagingSenderId: '982171502878',
    projectId: 'clontwitter',
    storageBucket: 'clontwitter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADsbjV4tu50bz4wLPX_IhuvedE5B-p81U',
    appId: '1:982171502878:ios:f4dbb197b44f631cac210f',
    messagingSenderId: '982171502878',
    projectId: 'clontwitter',
    storageBucket: 'clontwitter.firebasestorage.app',
    iosBundleId: 'com.example.twitterclon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADsbjV4tu50bz4wLPX_IhuvedE5B-p81U',
    appId: '1:982171502878:ios:f4dbb197b44f631cac210f',
    messagingSenderId: '982171502878',
    projectId: 'clontwitter',
    storageBucket: 'clontwitter.firebasestorage.app',
    iosBundleId: 'com.example.twitterclon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhL_H1TH5-nP2_bGiUn77FzGUslOqFsOc',
    appId: '1:982171502878:web:23be98dcd128c808ac210f',
    messagingSenderId: '982171502878',
    projectId: 'clontwitter',
    authDomain: 'clontwitter.firebaseapp.com',
    storageBucket: 'clontwitter.firebasestorage.app',
    measurementId: 'G-NBJ0KK3J8K',
  );

}